### ISSUE TITLE
review atomic primitives usage

### ISSUE THREAD

**Issue by fogti** [irrustible/ping-pong-cell#2]
This code seems to use a different, but yet similiar pattern as discussed here: https://github.com/reclutch-nursery/revenq/issues/3.

This code might have fixed this weakness (in that case I'm happy to replace my own half-baked implementations of this pattern with this crate (or maybe not, the license may be incompatible)), but I'm not entirely sure about that.

Another related issue is https://github.com/crossbeam-rs/crossbeam-utils/issues/2.

cc @stjepang
The code in this crate is probably correct, as it doesn't use the `Relaxed` ordering, right?

**Comment by ghost** [comment]
Looks correct. :) This is essentially a spinlock with a transactional api, and it correctly uses Acquire for locking and Release for unlocking.

**Comment by fogti** [comment]
Thanks.
